###########
# site.title

title:    'CSE 168 Homework Reports'
subtitle: 'Spring 2021'
mathjax: true

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-slate

